### ISSUE TITLE
Long strings will fall out of the textbox

### ISSUE THREAD

**Issue by SunTheCourier** [handihow/skilltree#12]
If you insert a long string into a skill text box the text will fall out of the box.
![Bug](https://user-images.githubusercontent.com/22406854/91761883-06c7e800-eb8a-11ea-9107-ca9649130b9d.png)

**Comment by handihow** [comment]
Long URL strings can be better handled as a link. You can then set a description on the link so that the text does not overflow.

In the text editor of the skill, you can select the text you want to add the link (url). The link button in the editor will be enabled. 

**Screenshots of rich text editor**

<img width="516" alt="Schermafbeelding 2020-09-01 om 10 30 07" src="https://user-images.githubusercontent.com/46277832/91827050-a5ae1c00-ec3e-11ea-9f0e-e4c7ccfbaeaf.png">

<img width="918" alt="Schermafbeelding 2020-09-01 om 10 29 58" src="https://user-images.githubusercontent.com/46277832/91826908-7b5c5e80-ec3e-11ea-9c55-8723079ed3e0.png">

**Alternatively, add link to the skill**

You can also add a link to the skill, separate from the description text. This is the button on the right side. You can search the link, it will attempt to get information about the link automatically and set that as title and description on the link. You can override this information. The link will remain as url, but the title will appear as text on your skill and users can click on that.

**Comment by handihow** [comment]
<img width="713" alt="Schermafbeelding 2020-09-01 om 10 35 58" src="https://user-images.githubusercontent.com/46277832/91827450-29680880-ec3f-11ea-8d6e-b594f4256b36.png">
